export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
   
      <div className="h-screen 
      flex items-center justify-center">{children}</div>
   
  )
}
