import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/nav-bar";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}  mx-auto min-w-screen min-h-screen`}>
        <div className="sm:px-6 md:px-0 max-w-6xl mx-auto">
        <NavBar />
        {children}
        </div>
        
        <Toaster />
        </body>

    </html>
  );
}
